name: Solor workflow


on:
  push: 


jobs: 
  practice-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Welcome message
        run: echo "This is my first solo CI"
        
      - name: if condition validation
        if: github.rf == 'refs/heads/main'
        run: echo "if condition is working"


